### ISSUE TITLE
User ID not created

### ISSUE THREAD

**Issue by kalyan711987kalyan** [geosparks/geospark-ios-sdk-example#1]
Hi, 

I have created bundle Id on your site.
Then used App key and secret key in app delegate and followed the step.
Now I'm creating the user

        GeoSpark.sharedInstance.createUser { (success, error, errorCode, userID) in {    }

This callback is not return, I tried with your sample also running in the device.

Any update over this ?

**Comment by jothipriyadharshanr** [comment]
Please check the latest documentation. https://geospark.co/docs/ios/
