### ISSUE TITLE
Problem using methods in app

### ISSUE THREAD

**Issue by gotcho** [geosparks/geospark-ios-sdk-example#3]
Hi!

Me again, now we have some troubles when trying to use any GeoSpark method (even in the test app)
For example:

`
        let deviceTokenForGeoSPark = tokenParts.joined()
        GeoSpark.didRegisterForRemoteNotificationsWithDeviceToken(deviceTokenForGeoSPark)
`

give us:

> 'String' is not convertible to 'GeoSpark'

**Comment by jothipriyadharshanr** [comment]
Hi, We will check and revert back as soon as possible.

Thanks.
